### ISSUE TITLE
from .VQ_VAE import Model

### ISSUE THREAD

**Issue by yishuaidu** [awei669/VQ-Font#2]
ModuleNotFoundError: No module named 'model.VQ_VAE'

**Comment by awei669** [comment]
Hi, you can delete this line of code directly. Since I deleted ./model/VQ_VAE.py, this implementation is now in ./model/VQ_VAE.ipynb. I will correct this problem, thanks for pointing this.

**Comment by awei669** [comment]
Close the issue, reopen the issue for any further questions.
