### ISSUE TITLE
train_3000.png这种是哪些需要这样命名呢?

### ISSUE THREAD

**Issue by aceliuchanghong** [awei669/VQ-Font#24]
4.Organize directories structure as below, and train_3000.png means draw the image from train_unis: ["4E00", "4E01", ...].
这儿是需要把字体转图片的每个字体的所有图片文件再重命名为train_1.png..train_100.png..train_1000.png..这种形式吗?没太懂,虚心求教

**Comment by aceliuchanghong** [comment]
![image](https://github.com/user-attachments/assets/b014ddc5-57cd-4e10-bdf6-6f4bf1cabae5)
![image](https://github.com/user-attachments/assets/a0a061b8-1aa6-4916-b779-d5e57489d986)
并没有叫train_1.png这样,不知道对吗?

**Comment by awei669** [comment]
All images are named by 'characters + .png', such as ‘阿.png’. Organize directories structure as below, and train_3000.png means draw the image from train_unis: ["4E00", "4E01", ...].

不需要命名为train_1.png，所有图片都是以字符名称直接命名的，train_3000仅代表字符来自训练集合。

**Comment by aceliuchanghong** [comment]
哦,这个意思啊,谢谢了,这儿的意思其实是临时区的一个名字而已,是吧,谢谢作者
