### ISSUE TITLE
lmdb包准备问题

### ISSUE THREAD

**Issue by JstYY** [awei669/VQ-Font#6]
不知道哪一步准备lmdb包出现问题：
我的第二阶段数据准备文件夹为second，其中包含了与第一阶段不同的字体的content，train，val三个文件夹，其中图片数为2：8：2。

我运行build_trainset:
python3 build_meta4train.py \
--saving_dir F:\python_project\VQ-Font-main\VQ-Font-main\results\your_task_name \
--content_font F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\content \
--train_font_dir F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\train \
--val_font_dir F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\val \
--seen_unis_file F:\python_project\VQ-Font-main\VQ-Font-main\meta\train_unis.json \
--unseen_unis_file F:\python_project\VQ-Font-main\VQ-Font-main\meta\val_unis.json \
分别对应：lmdb的储存位置/第二阶段content图片/第二阶段train图片/第二阶段val图片/train内字体的图片对应的json文件/val内图片字体的对应图片

结果报错：
F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\train
num of fonts:  2
ttf_path_list: 3
100%|███████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "build_meta4train.py", line 213, in <module>
    build_meta4train_lmdb(args)
  File "build_meta4train.py", line 139, in build_meta4train_lmdb
    valid_dict = save_lmdb(lmdb_path, out_dict)
  File "build_meta4train.py", line 26, in save_lmdb
    env = lmdb.open(env_path, map_size=1024 ** 4)
lmdb.Error: F:\python_project\VQ-Font-main\VQ-Font-main\results\your_task_name\lmdb: ���̿ռ䲻�㡣

csdn内让我改小 map_size大小，但是改后报错：
F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\train
num of fonts:  2
ttf_path_list: 3
100%|███████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
  0%|                                                           | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "build_meta4train.py", line 213, in <module>
    build_meta4train_lmdb(args)
  File "build_meta4train.py", line 139, in build_meta4train_lmdb
    valid_dict = save_lmdb(lmdb_path, out_dict)
  File "build_meta4train.py", line 46, in save_lmdb
    char_img = Image.fromarray(char_img)
  File "F:\python\lib\site-packages\PIL\Image.py", line 3078, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'

运行我的文件后已经得到了一个lmdb包，但是运行第二阶段train.py出现报错：Traceback (most recent call last):
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 221, in <module>
    main()
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 217, in main
    train(args, cfg)
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 140, in train
    drop_last=True)
  File "F:\python_project\VQ-Font-main\VQ-Font-main\datasets\__init__.py", line 24, in get_comb_trn_loader
    collate_fn=dset.collate_fn, **kwargs)
  File "F:\python\lib\site-packages\torch\utils\data\dataloader.py", line 347, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "F:\python\lib\site-packages\torch\utils\data\sampler.py", line 106, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "F:\python\lib\site-packages\torch\utils\data\sampler.py", line 114, in num_samples
    return len(self.data_source)
  File "F:\python_project\VQ-Font-main\VQ-Font-main\datasets\dataset_transformer.py", line 116, in __len__
    return sum([len(v) for v in self.avails.values()])
AttributeError: 'list' object has no attribute 'values'
显示我的train的json文件内为列表而非字典

应该是我的lmdb包准备有问题，但是我实在是不知道哪里有问题，改后问题也没有解决，求帮助！！！！感谢！！

**Comment by awei669** [comment]
你好，感谢对我们工作的关注～

1）图片数为2：8：2 ？构建lmdb时所有font当中的字符数量应该是一样的，即包含train_unis.json + val_unis.json中的所有字符图像，注意图片命名格式为‘啊.png’。

2）你的font数量过少，可以去字体网站上多收集一些ttf文件。

3）--content_font 这个路径应该是内容图片路径，--train_font_dir和--val_font_dir这两个路径则应该是font的上一级。

<img width="483" alt="image" src="https://github.com/awei669/VQ-Font/assets/68525870/99df6d6e-69ca-4b75-bdc6-5e2117b1cc02">

如图，--content_font应该为 ./data/content/kaiti/，--train_font_dir为 ./data/train/，--val_font_dir为 ./data/val/，kaiti也是第二阶段训练的内容字体的名称。

你的问题感觉是问题1）图片数量没有一致，构建lmdb时content里面不仅要放训练也要放测试的图片。

**Comment by JstYY** [comment]
你好，我现在的准备数据详情如下：
second
>content
    >华康POP HandelGotD-Cxibei
         156个华康风格图片（字为train与val内的所有文字）
>train
    >train font1
        131个a类风格的字体图片
    >train font2
        131个b类风格字体图片
    >train font3
        131个c类字体图片
>val
    >val font1
         25个a类风格图片
    >val font2
         25个b类风格图片
    >val font3
         25个c类风格图片
         
       以上图片的命名均为“啊.png”；
我的train_unis.json与val_unis.json内为上述train与val中的131个汉字与25个汉字的编码列表；

我的bulid文件为：
python3 build_meta4train.py
--saving_dir "F:\python_project\VQ-Font-main\VQ-Font-main\results\your_task_name"
--content_font "F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\content"
--train_font_dir "F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\train"
--val_font_dir "F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\val"
--seen_unis_file "F:\python_project\VQ-Font-main\VQ-Font-main\meta\train_unis.json"
--unseen_unis_file "F:\python_project\VQ-Font-main\VQ-Font-main\meta\val_unis.json"
       
 在cmd中运行这个文件没有报错，然后我运行了
  python F:\python_project\VQ-Font-main\VQ-Font-main\train.py task_name F:\python_project\VQ-Font-main\VQ-Font-main\cfgs\custom.yaml
  
  这个语句，其中的custom.yaml内路径如下：
vae_pth: F:\python_project\VQ-Font-main\VQ-Font-main\weight\VQ-VAE_Parms_chn_.pth # path/to/save/pre-trained model
sim_path: F:\python_project\VQ-Font-main\VQ-Font-main\weight\all_char_similarity_unicode.json # path/to/save/content_similarity
work_dir: F:\python_project\VQ-Font-main\VQ-Font-main\results\your_task_name # workspace
data_path: F:\python_project\VQ-Font-main\VQ-Font-main\results\your_task_name\lmdb # path/to/saved/lmdb
data_meta: F:\python_project\VQ-Font-main\VQ-Font-main\meta\train_unis.json # meta/train.json
all_content_json: F:\python_project\VQ-Font-main\VQ-Font-main\meta\trian_val_all_characters.json
content_font: "华康POP HandelGotD-Cxibei" # content font

最后的结果错误依然为：
Traceback (most recent call last):
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 221, in <module>
    main()
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 217, in main
    train(args, cfg)
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 140, in train
    drop_last=True)
  File "F:\python_project\VQ-Font-main\VQ-Font-main\datasets\__init__.py", line 24, in get_comb_trn_loader
    collate_fn=dset.collate_fn, **kwargs)
  File "F:\python\lib\site-packages\torch\utils\data\dataloader.py", line 347, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "F:\python\lib\site-packages\torch\utils\data\sampler.py", line 106, in __init__
    if not isinstance(self.num_samples, int) or self.num_samples <= 0:
  File "F:\python\lib\site-packages\torch\utils\data\sampler.py", line 114, in num_samples
    return len(self.data_source)
  File "F:\python_project\VQ-Font-main\VQ-Font-main\datasets\dataset_transformer.py", line 116, in __len__
    return sum([len(v) for v in self.avails.values()])
AttributeError: 'list' object has no attribute 'values'

数据集准备很久了，拜托帮帮我吧，一直没办法成功训练，心态要崩了！！！！！感谢感谢！

**Comment by awei669** [comment]
你的数据集组织仍然是不对的，>train font1 当中也应当放置156字符图片（为train与val内的所有文字）。

修改之后再次构建lmdb数据集。

**Comment by JstYY** [comment]
你好，我按照你说的把train font1内改成了156个字体图片，但是这样子我的bulid文件运行结果就没有lmdb包了，得到的是四个文件夹为：runs,logs,images,checkpoints ,  然后在cmd直接运行训练会出现lmdb的错误，提示没有lmdb文件；
报错如下：
Traceback (most recent call last):
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 221, in <module>
    main()
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 217, in main
    train(args, cfg)
  File "F:\python_project\VQ-Font-main\VQ-Font-main\train.py", line 123, in train
    env = load_lmdb(cfg.data_path)  # 载入数据库环境lmdb
  File "F:\python_project\VQ-Font-main\VQ-Font-main\datasets\lmdbutils.py", line 29, in load_lmdb
    meminit=False,
lmdb.Error: F:\python_project\VQ-Font-main\VQ-Font-main\results\your_task_name\lmdb: ϵͳ�Ҳ���ָ����·����


之后我把train font1/2/3 内全部换成了a/b/c风格的156个图片，则我的build脚本运行结果不会在我的任务文件夹内构建任何文件夹
是哪里有问题呢？

**Comment by awei669** [comment]
在以上基础上，修改以下路径，另外，请仔细查看上面我给你回复的内容；并仔细检查train.json中的各字段信息。

--content_font "F:\python_project\VQ-Font-main\VQ-Font-main\Font_Directory\second\content\华康POP HandelGotD-Cxibei\"

**Comment by JstYY** [comment]
我认真的读了你的回复，请您看仔细我的提问，我在上一条提问中就已经单独修改了train font1内改成了156个字体图片，其中包含了val font1的图片，其他的train_font没有改动，之后结果如上条提问，现在我在此基础上修改了我的content_font,也检测了我的train.json内为156个字体图片对应的编码，包含val中的字体编码，但是运行我的build脚本后，我的result文件夹内没有出现任何文件夹，请问这是什么原因？

**Comment by awei669** [comment]
请注意，所有训练和测试字体当中都应该包含156张字体图片，不仅是我说的train font1。

content
>华康POP HandelGotD-Cxibei
156个华康风格图片（字为train与val内的所有文字）
train
>train font1
156个a类风格的字体图片
>train font2
156个b类风格字体图片
>train font3
156个c类字体图片
val
>val font1
156个a类风格图片
>val font2
156个b类风格图片
>val font3
156个c类风格图片

我第一次回复的图片中就说明了这个问题。

**Comment by JstYY** [comment]
你好，我按照你的说法还是同样的错误，请问可不可以给我发一下你们的数据准备包呢

**Comment by hofirstb19** [comment]
您好，请问这个问题，您解决了吗？我也遇到相同问题了，然而在我修改build_meta4train.py文件21行map_size大小后，并没有报出lmdb问题了，而是出现了cv2.imread(img_path)返回None值的问题，除了文件命名为中文外，路径中并无其他含中文字段的部分？请问这种情况应该怎么处理呢？

我准备的数据如下图形式，按照文档要求建立：
![微信图片_20240304151307](https://github.com/awei669/VQ-Font/assets/54053805/8dbb6915-2402-4606-b98e-bb77a0bfce1c)


我使用Image.open(img_path)与cv2.open(img_path, 0)的输出如下：
![2](https://github.com/awei669/VQ-Font/assets/54053805/2fb3010f-4ced-450c-8d61-34613744ef19)

**Comment by hofirstb19** [comment]
您好，请问这个问题，您解决了吗？我也遇到相同问题了，然而在我修改build_meta4train.py文件21行map_size大小后，并没有报出lmdb问题了，而是出现了cv2.imread(img_path)返回None值的问题，除了文件命名为中文外，路径中并无其他含中文字段的部分？我最终将build_meta4train.py文件39行的图片读入方式改为了Image.open，再将其转为cv2所需格式，完成了此步操作。

我准备的数据如下图形式，按照文档要求建立：
![微信图片_20240304151307](https://github.com/awei669/VQ-Font/assets/54053805/8dbb6915-2402-4606-b98e-bb77a0bfce1c)


我使用Image.open(img_path)与cv2.open(img_path, 0)的输出如下：
![2](https://github.com/awei669/VQ-Font/assets/54053805/2fb3010f-4ced-450c-8d61-34613744ef19)

**Comment by awei669** [comment]
@hofirstb19 你好，你的内容字体路径要精确到图片上一级。根据你组织的数据结构，构建lmdb的脚本应该如下：

```
python3 build_meta4train.py \
--saving_dir ../results/test/ \
--content_font ../data/content_imgs/train_val \
--train_font_dir ../data/train_font/ \
--val_font_dir ../data/val_font/ \
--seen_unis_file ../meta/train_unis.json \
--unseen_unis_file ../meta/val_unis.json 
```

我重新在我的机器上测试了代码，可以正常生成lmdb文件和train.json，lmdb生成完后可以自行检查生成的meta当中的json文件正确与否。

以下是我Clone完整项目后并运行脚本的过程和结果：

<img width="1505" alt="image" src="https://github.com/awei669/VQ-Font/assets/68525870/42b86af6-fe38-444d-8760-81b24d35c72f">

**Comment by hofirstb19** [comment]
你好，我按照你的建议更改了lmdb的构建方式，并且重新执行了预训练和正式训练的过程。train.py的执行结果如下：
INFO::03/11 14:33:55 | Unique name: test_1
INFO::03/11 14:33:55 | Get dataset ...
INFO::03/11 14:33:55 | Build Few-shot model ...
INFO::03/11 14:33:56 | Load pre-train model...
INFO::03/11 14:34:01 | Start training FewShot ...
INFO::03/11 14:45:17 |&nbsp; &nbsp;Step&nbsp; &nbsp; 1000: L1&nbsp; 0.5255&nbsp; &nbsp;Contrastive&nbsp; 1.5240&nbsp; D&nbsp; &nbsp;3.519&nbsp; G&nbsp; &nbsp;1.058&nbsp; B_stl&nbsp; &nbsp;2.0&nbsp; B_trg&nbsp; &nbsp;2.0
INFO::03/11 14:57:21 |&nbsp; &nbsp;Step&nbsp; &nbsp; 2000: L1&nbsp; 0.4396&nbsp; &nbsp;Contrastive&nbsp; 1.3457&nbsp; D&nbsp; &nbsp;3.485&nbsp; G&nbsp; &nbsp;1.151&nbsp; B_stl&nbsp; &nbsp;2.0&nbsp; B_trg&nbsp; &nbsp;2.0
INFO::03/11 15:08:41 |&nbsp; &nbsp;Step&nbsp; &nbsp; 3000: L1&nbsp; 0.4200&nbsp; &nbsp;Contrastive&nbsp; 1.2732&nbsp; D&nbsp; &nbsp;3.454&nbsp; G&nbsp; &nbsp;1.608&nbsp; B_stl&nbsp; &nbsp;2.0&nbsp; B_trg&nbsp; &nbsp;2.0
INFO::03/11 15:19:50 |&nbsp; &nbsp;Step&nbsp; &nbsp; 4000: L1&nbsp; 0.3992&nbsp; &nbsp;Contrastive&nbsp; 1.2233&nbsp; D&nbsp; &nbsp;3.387&nbsp; G&nbsp; &nbsp;1.935&nbsp; B_stl&nbsp; &nbsp;2.0&nbsp; B_trg&nbsp; &nbsp;2.0
INFO::03/11 15:31:13 |&nbsp; &nbsp;Step&nbsp; &nbsp; 5000: L1&nbsp; 0.3866&nbsp; &nbsp;Contrastive&nbsp; 1.2186&nbsp; D&nbsp; &nbsp;3.369&nbsp; G&nbsp; &nbsp;1.896&nbsp; B_stl&nbsp; &nbsp;2.0&nbsp; B_trg&nbsp; &nbsp;2.0
INFO::03/11 15:31:13 | Validation at Epoch = 2.667
Killed



然而，在我执行推断过程的时候，报错如下：
Traceback (most recent call last):
&nbsp; File "inference.py", line 248, in <module&gt;
&nbsp; &nbsp; eval_ckpt(args, cfg, avail, target_root)
&nbsp; File "inference.py", line 140, in eval_ckpt
&nbsp; &nbsp; gen.load_state_dict(weight)
&nbsp; File "/home/j831/anaconda3/envs/vq/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
&nbsp; &nbsp; self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
&nbsp; &nbsp; &nbsp; &nbsp; Missing key(s) in state_dict: "component_encoder.layers.0.conv.weight", "component_encoder.layers.0.conv.bias", "component_encoder.layers.1.conv.weight", "component_encoder.layers.1.conv.bias", "component_encoder.layers.2.conv.weight", "component_encoder.layers.2.conv.bias", "component_encoder.layers.3.conv1.conv.weight", "component_encoder.layers.3.conv1.conv.bias", "component_encoder.layers.3.conv2.conv.weight", "component_encoder.layers.3.conv2.conv.bias", "component_encoder.layers.4.conv1.conv.weight", "component_encoder.layers.4.conv1.conv.bias", "component_encoder.layers.4.conv2.conv.weight", "component_encoder.layers.4.conv2.conv.bias", "component_encoder.layers.5.conv1.conv.weight", "component_encoder.layers.5.conv1.conv.bias", "component_encoder.layers.5.conv2.conv.weight", "component_encoder.layers.5.conv2.conv.bias", "component_encoder.layers.5.skip.weight", "component_encoder.layers.5.skip.bias", "component_encoder.layers.6.conv1.conv.weight", "component_encoder.layers.6.conv1.conv.bias", "component_encoder.layers.6.conv2.conv.weight", "component_encoder.layers.6.conv2.conv.bias", "Get_style_components.linears_key.weight", "Get_style_components.linears_value.weight", "Get_style_components.linears_query.weight", "Get_style_components.multihead_concat_fc.weight", "Get_style_components.layer_norm.weight", "Get_style_components.layer_norm.bias", "Get_style_components_1.linears_key.weight", "Get_style_components_1.linears_value.weight", "Get_style_components_1.linears_query.weight", "Get_style_components_1.multihead_concat_fc.weight", "Get_style_components_1.layer_norm.weight", "Get_style_components_1.layer_norm.bias", "Get_style_components_2.linears_key.weight", "Get_style_components_2.linears_value.weight", "Get_style_components_2.linears_query.weight", "Get_style_components_2.multihead_concat_fc.weight", "Get_style_components_2.layer_norm.weight", "Get_style_components_2.layer_norm.bias", "cam.linears_key.weight", "cam.linears_value.weight", "cam.linears_query.weight", "cam.multihead_concat_fc.weight", "cam.layer_norm.weight", "cam.layer_norm.bias", "content_encoder.net.0.conv.weight", "content_encoder.net.0.conv.bias", "content_encoder.net.1.conv.weight", "content_encoder.net.1.conv.bias", "content_encoder.net.2.conv.weight", "content_encoder.net.2.conv.bias", "content_encoder.net.3.conv.weight", "content_encoder.net.3.conv.bias", "content_encoder.net.4.conv.weight", "content_encoder.net.4.conv.bias", "decoder.layers.0.conv1.conv.weight", "decoder.layers.0.conv1.conv.bias", "decoder.layers.0.conv2.conv.weight", "decoder.layers.0.conv2.conv.bias", "decoder.layers.1.conv1.conv.weight", "decoder.layers.1.conv1.conv.bias", "decoder.layers.1.conv2.conv.weight", "decoder.layers.1.conv2.conv.bias", "decoder.layers.2.conv1.conv.weight", "decoder.layers.2.conv1.conv.bias", "decoder.layers.2.conv2.conv.weight", "decoder.layers.2.conv2.conv.bias", "decoder.layers.3.conv.weight", "decoder.layers.3.conv.bias", "decoder.layers.4.conv.weight", "decoder.layers.4.conv.bias", "decoder.layers.5.conv.weight", "decoder.layers.5.conv.bias", "decoder.layers.6.conv.weight", "decoder.layers.6.conv.bias", "Integrator.integrate_layer.conv.weight", "Integrator.integrate_layer.conv.bias", "Integrator_local.integrate_layer.conv.weight", "Integrator_local.integrate_layer.conv.bias".&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; Unexpected key(s) in state_dict: "_encoder.net.0.conv.weight", "_encoder.net.0.conv.bias", "_encoder.net.1.conv.weight", "_encoder.net.1.conv.bias", "_encoder.net.2.conv.weight", "_encoder.net.2.conv.bias", "_encoder.net.3.conv.weight", "_encoder.net.3.conv.bias", "_encoder.net.4.conv.weight", "_encoder.net.4.conv.bias", "_vq_vae._embedding.weight", "_decoder.layers.0.conv1.conv.weight", "_decoder.layers.0.conv1.conv.bias", "_decoder.layers.0.conv2.conv.weight", "_decoder.layers.0.conv2.conv.bias", "_decoder.layers.1.conv1.conv.weight", "_decoder.layers.1.conv1.conv.bias", "_decoder.layers.1.conv2.conv.weight", "_decoder.layers.1.conv2.conv.bias", "_decoder.layers.2.conv1.conv.weight", "_decoder.layers.2.conv1.conv.bias", "_decoder.layers.2.conv2.conv.weight", "_decoder.layers.2.conv2.conv.bias", "_decoder.layers.3.conv.weight", "_decoder.layers.3.conv.bias", "_decoder.layers.4.conv.weight", "_decoder.layers.4.conv.bias", "_decoder.layers.5.conv.weight", "_decoder.layers.5.conv.bias", "_decoder.layers.6.conv.weight", "_decoder.layers.6.conv.bias".&nbsp;





custom.yaml中关于文件的配置如下：
vae_pth: ./weight/VQ-VAE_Parms_chn_1.pth # path/to/save/pre-trained model
sim_path: ./weight/all_char_similarity_unicode.json # path/to/save/content_similarity
work_dir: ./results/test3/ # workspace
data_path: ./results/test3/lmdb/  # path/to/saved/lmdb
data_meta: ./results/test3/meta/train.json  # meta/train.json
all_content_json: ./meta/trian_val_all_characters.json
content_font: "train_val" # content font

inference.sh的配置如下：
python3 inference.py ./cfgs/custom.yaml \
--weight ./weight/VQ-VAE_Parms_chn_1.pth \
--content_font ./data/content_imgs/train_val \
--img_path ./data/content_imgs/val \
--saving_root ./infer_res





请问：是不是我相关配置又出现了什么问题？导致最终推断过程中，生成器那一部分的参数导入失败了？


何前宝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "awei669/VQ-Font"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月9日(星期六) 凌晨3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [awei669/VQ-Font] lmdb包准备问题 (Issue #6)





 
@hofirstb19 你好，你的内容字体路径要精确到图片上一级。根据你组织的数据结构，构建lmdb的应该脚本如下：
 python3 build_meta4train.py \ --saving_dir ../results/test/ \ --content_font ../data/content_imgs/train_val \ --train_font_dir ../data/train_font/ \ --val_font_dir ../data/val_font/ \ --seen_unis_file ../meta/train_unis.json \ --unseen_unis_file ../meta/val_unis.json   
我重新在我的机器上测试了代码，可以正常生成lmdb文件和train.json，lmdb生成完后可以自行检查生成的meta当中的json文件正确与否。
 
以下是我Clone完整项目后并运行脚本的过程和结果：
 image.png (view on web)

**Comment by awei669** [comment]
@hofirstb19 --weigh应该载入字体模型参数而不是VQ-VAE的参数，找到第二阶段训练时保存的checkpoint并载入。

**Comment by hofirstb19** [comment]
但是，第二阶段训练后保存的包括checkpoint、images都是空文件夹。第二阶段使用的是
python3 train.py test_1 cfgs/custom.yaml

其中custom.yaml的仅关于文件配置的设置有所修改，具体如下：
vae_pth: ./weight/VQ-VAE_Parms_chn_1.pth # path/to/save/pre-trained model
sim_path: ./weight/all_char_similarity_unicode.json # path/to/save/content_similarity
work_dir: ./results/test3/ # workspace
data_path: ./results/test3/lmdb/  # path/to/saved/lmdb
data_meta: ./results/test3/meta/train.json  # meta/train.json
all_content_json: ./meta/trian_val_all_characters.json
content_font: "train_val" # content font

最终，训练到step 5000时，出现了下面情况：
............................................................................................................................................................................................................
INFO::03/11 15:31:13 |&nbsp; &nbsp;Step&nbsp; &nbsp; 5000: L1&nbsp; 0.3866&nbsp; &nbsp;Contrastive&nbsp; 1.2186&nbsp; D&nbsp; &nbsp;3.369&nbsp; G&nbsp; &nbsp;1.896&nbsp; B_stl&nbsp; &nbsp;2.0&nbsp; B_trg&nbsp; &nbsp;2.0
INFO::03/11 15:31:13 | Validation at Epoch = 2.667
Killed

............................................................................................................................................................................................................
是训练的时候意外终止导致checkpoint、images都是空文件夹吗？


&nbsp;


何前宝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wei ***@***.***&gt;; 
发送时间: 2024年3月11日(星期一) 晚上9:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [awei669/VQ-Font] lmdb包准备问题 (Issue #6)





 
@hofirstb19 --weigh应该载入字体模型参数而不是VQ-VAE的参数，找到第二阶段训练时保存的checkpoint并载入。

**Comment by awei669** [comment]
> 但是，第二阶段训练后保存的包括checkpoint、images都是空文件夹。第二阶段使用的是 python3 train.py test_1 cfgs/custom.yaml 其中custom.yaml的仅关于文件配置的设置有所修改，具体如下： vae_pth: ./weight/VQ-VAE_Parms_chn_1.pth # path/to/save/pre-trained model sim_path: ./weight/all_char_similarity_unicode.json # path/to/save/content_similarity work_dir: ./results/test3/ # workspace data_path: ./results/test3/lmdb/ # path/to/saved/lmdb data_meta: ./results/test3/meta/train.json # meta/train.json all_content_json: ./meta/trian_val_all_characters.json content_font: "train_val" # content font 最终，训练到step 5000时，出现了下面情况： ............................................................................................................................................................................................................ INFO::03/11 15:31:13 |&nbsp; &nbsp;Step&nbsp; &nbsp; 5000: L1&nbsp; 0.3866&nbsp; &nbsp;Contrastive&nbsp; 1.2186&nbsp; D&nbsp; &nbsp;3.369&nbsp; G&nbsp; &nbsp;1.896&nbsp; B_stl&nbsp; &nbsp;2.0&nbsp; B_trg&nbsp; &nbsp;2.0 INFO::03/11 15:31:13 | Validation at Epoch = 2.667 Killed ............................................................................................................................................................................................................ 是训练的时候意外终止导致checkpoint、images都是空文件夹吗？ &nbsp; 何前宝 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Wei ***@***.***&gt;; 发送时间: 2024年3月11日(星期一) 晚上9:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [awei669/VQ-Font] lmdb包准备问题 (Issue #6) @hofirstb19 --weigh应该载入字体模型参数而不是VQ-VAE的参数，找到第二阶段训练时保存的checkpoint并载入。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

修改 cfgs/custom.yaml

```
print_freq: 1000
val_freq: 5000
save_freq: 50000
tb_freq: 10000
```

中val_freq和save_freq参数。

建议仔细阅读代码后提问，或者从FFG-benchmarks开始阅读：https://github.com/clovaai/fewshot-font-generation

**Comment by Djs-Champion** [comment]
你好请问数据集中的train和val文件夹中的内容是一模一样的吗

**Comment by awei669** [comment]
@Djs-Champion 在第二阶段构建lmdb时，content以及train和val下面字体文件包含的图片内容是一样的，均包含train_unis + val_unis所有字符。
